In [1]:
import pandas as pd

In [8]:
df= pd.read_csv(r"C:\Users\aditi\my desktop\desktop\D08-HealthInfrastructure_1.csv")

In [9]:
df.head()

,City Name,Zone Name,Ward Name,Ward No.,Facility Name,Type (Hospital / Nursing Home / Lab),Class : (Public / Private),Level (Primary / Secondary / Tertiary),Pharmacy Available : Yes/No,Number of Beds in Emergency Wards,Number of Beds in facility type,Number of Doctors / Physicians,Number of Nurses,Number of Midwives Professional,Average Monthly Patient Footfall,Ambulance Service Available,Count of Ambulance
0,RAIPUR,1,YATIYATAN LAL WARD,4,om hari hospital,Nursing,Private,Tertiary,Yes,0,11,22,22,7,1,Yes,2
1,RAIPUR,1,BANJARI MAMA WARD,5,jk hospital,Hospital,Private,Tertiary,Yes,1,1,3,1,7,2,Yes,3
2,RAIPUR,1,VIRANGNA AVA.NTI BAI WARD,6,ak hospital,Nursing,Private,Secondary,Yes,2,1,2,1,7,2,Yes,2
3,RAIPUR,1,VIR SHIVAJI WARD,7,mr hospital,Hospital,Public,Tertiary,Yes,3,12,23,1,7,3,Yes,2
4,RAIPUR,1,NETAJI KANHAIYALAL BAZARI WARD,8,om hari hospital,Nursing,Private,Tertiary,Yes,4,2,44,11,7,4,Yes,2

In [10]:
df.tail()

,City Name,Zone Name,Ward Name,Ward No.,Facility Name,Type (Hospital / Nursing Home / Lab),Class : (Public / Private),Level (Primary / Secondary / Tertiary),Pharmacy Available : Yes/No,Number of Beds in Emergency Wards,Number of Beds in facility type,Number of Doctors / Physicians,Number of Nurses,Number of Midwives Professional,Average Monthly Patient Footfall,Ambulance Service Available,Count of Ambulance
1339,Udaipur,4,al Bahudur Shashtri Ward,51,Arogyam Ayurved Hospital,Hospital,Private,Tertiary,Yes,0,2,3,4,5,4,Yes,3
1340,Udaipur,4,al Bahudur Shashtri Ward,52,Dr. Atray Eye Hospital,Hospital,Private,Secondary,Yes,0,2,34,4,5,3,Yes,3
1341,Udaipur,5,al Bahudur Shashtri Ward,53,Partani Ent Hospital,Hospital,Private,Secondary,Yes,0,7,4,4,5,22,Yes,3
1342,Udaipur,5,al Bahudur Shashtri Ward,54,Hari Om Hospital,Hospital,Private,Secondary,Yes,0,7,4,4,5,23,Yes,3
1343,Udaipur,5,al Bahudur Shashtri Ward,55,Shantiraj Hospital Pvt Ltd,Hospital,Private,Tertiary,Yes,0,7,44,4,55,3,Yes,3

In [11]:
df.shape

(1344, 17)

In [12]:
df.columns

Index(['City Name', 'Zone Name', 'Ward Name', 'Ward No.', 'Facility Name',
       'Type  (Hospital / Nursing Home / Lab)', ' Class : (Public / Private)',
       'Level (Primary / Secondary / Tertiary)', 'Pharmacy Available : Yes/No',
       'Number of Beds in Emergency Wards ', 'Number of Beds in facility type',
       'Number of Doctors / Physicians', 'Number of Nurses',
       'Number of Midwives Professional ', 'Average Monthly Patient Footfall',
       'Ambulance Service Available', 'Count of Ambulance'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1344 entries, 0 to 1343
Data columns (total 17 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   City Name                               1344 non-null   object
 1   Zone Name                               1344 non-null   int64
 2   Ward Name                               1344 non-null   object
 3   Ward No.                                1344 non-null   int64
 4   Facility Name                           1344 non-null   object
 5   Type  (Hospital / Nursing Home / Lab)   1344 non-null   object
 6    Class : (Public / Private)             1344 non-null   object
 7   Level (Primary / Secondary / Tertiary)  1344 non-null   object
 8   Pharmacy Available : Yes/No             1344 non-null   object
 9   Number of Beds in Emergency Wards       1344 non-null   int64
 10  Number of Beds in facility type         1344 non-null   int64
 11  Number of Doctors / Physicians          1344 non-null   int64
 12  Number of Nurses                        1344 non-null   int64
 13  Number of Midwives Professional         1344 non-null   int64
 14  Average Monthly Patient Footfall        1344 non-null   int64
 15  Ambulance Service Available             1344 non-null   object
 16  Count of Ambulance                      1344 non-null   int64
dtypes: int64(9), object(8)
memory usage: 178.6+ KB